<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="net" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="distance" value="-5" /> <!-- distance from arm-->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="100" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="4" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/net.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />
  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="link1"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
  </joint>
  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="${distance} 0.5 ${height1/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${distance} 0.5 ${height1/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${distance} 0.5 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
    izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Box Links-->
  <link name="box1">
    <collision>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 1 1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 1 1"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  <joint name="boxjoint1" type="fixed">
    <parent link="link1"/>
    <child link="box1"/>
    <origin xyz="0.5 0.7 4" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="box2">
    <collision>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 1 1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 1 1"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  <joint name="boxjoint2" type="fixed">
    <parent link="link1"/>
    <child link="box2"/>
    <origin xyz="-0.5 0.7 4" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="box3">
    <collision>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="1 0.1 1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="1 0.1 1"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  <joint name="boxjoint3" type="fixed">
    <parent link="link1"/>
    <child link="box3"/>
    <origin xyz="0 1.2 4" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="box4">
    <collision>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="1 0.1 1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${distance} 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="1 0.1 1"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  <joint name="boxjoint4" type="fixed">
    <parent link="link1"/>
    <child link="box4"/>
    <origin xyz="0 0.2 4" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- End Box Links-->
</robot>